# Generated by Django 3.0.7 on 2020-06-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
